# -*- coding: utf-8 -*-
"""MonitoriaRR_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r0BM7lWRGYkqKQylAUvHJVFIVO8XKcgm
"""

import numpy as np


def relacion_recurrencia(n : int):
  # Definir el caso base. f(0) = 8, f(1) = 1/(2*\sqrt{2})
  if n == 0:
    return 8.0
  elif n == 1:
    return 2**(-3/2) 
  return np.sqrt(relacion_recurrencia(n-2)/relacion_recurrencia(n-1))

def no_recurrencia(n : int):
  return 2**(0.5**n + 2*(-1)**n)

for n in range(11):
  print(f'n={n}.\t Resultado de la RR: {np.round(relacion_recurrencia(n), 3)}.\tResultado Expresión cerrada: {np.round(no_recurrencia(n), 3)}.')